#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

touch test.foam

runApplication blockMesh

#runApplication decomposePar

#runParallel setFields

#runParallel $(getApplication)

runApplication setFields

runApplication $(getApplication)
#------------------------------------------------------------------------------
