name: C/C++ CI

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#      run: ./configure
    - name: install fftw3 (dependency)
      run: sudo apt-get install fftw3 libfftw3-dev
    - name: make
      working-directory: ./src
      run: make
    - name: create binary tar.gz
      run: |
        mkdir release
        cp ./builds/linux64/libCFDwavemaker_swd_openmp.a ./release/.
        cp ./builds/linux64/libCFDwavemaker_swd_openmp.so ./release/.
        cp ./src/CFDwavemaker.h ./release/.
        tar -zcvf cfdwavemaker_binary_release.tar.gz release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: cfdwavemaker_binary_release.tar.gz
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
