name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#      run: ./configure
    - name: install fftw3 (dependency)
      run: sudo apt-get install fftw3 libfftw3-dev
    - name: make
      working-directory: ./src
      run: make
    - name: create binary tar.gz
      run: |
        mkdir release
        cp ./builds/linux64/libCFDwavemaker_swd_openmp.a ./release/.
        cp ./builds/linux64/libCFDwavemaker_swd_openmp.so ./release/.
        cp ./src/CFDwavemaker.h ./release/.
        tar -zcvf cfdwavemaker_binary_release.tar.gz release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
